/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.IOException;

public class App {


    public static void main(String[] args) throws IOException {
        try {
            GetMeAQuote getMeAQuote = null;
            if (args.length > 0){
            String filePath = args[0];
                getMeAQuote = new GetMeAQuote(filePath);
            } else {
                getMeAQuote = new GetMeAQuote();
            }
            String result = getMeAQuote.getTheQuotes();
            System.out.println(result);
        } catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
}

