/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;


import java.util.ArrayList;

import java.util.*;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void returnMethodReturnsRollsInAnArray() {
        Library sut = new Library();
        assertEquals(sut.roll(3).length, 3);
    }


    @Test void containsDuplicatesMethodReturnsTrueIfDuplicates() {
        Library sut = new Library();
        int[] testArr = {0,1,1};
        System.out.println(sut.containsDuplicate(testArr));
        assertTrue(sut.containsDuplicate(testArr));
    }

    @Test void calcAvgOfArrayReturnsAverage() {
        Library sut = new Library();
        int[] testArr = {50, 100, 150, 200, 250};
        assertEquals(sut.calcAvgOfArray(testArr), 150);
    }

    @Test void lowestAvgArrReturnsArrayLowestAvg() {

    }
    @Test void analyzeWeatherDataTest(){
        Library sut = new Library();
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] test = sut.lowestAvgArr(weeklyMonthTemperatures);
        assertEquals(Arrays.toString(test),"[55, 54, 60, 53, 59, 57, 61]");

        assertEquals(sut.analyzeWeatherData(weeklyMonthTemperatures), "High: 72"
                + "\n" + "Low: 51"
                + "\n" + "Never saw temperature: 63"
                + "\n" + "Never saw temperature: 67"
                + "\n" + "Never saw temperature: 68"
                + "\n" + "Never saw temperature: 69"+ "\n");
    }

    @Test void tallyTest(){
        Library sut = new Library();
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        String winner = sut.tally(votes);
        assertEquals(winner, "Bush");
        System.out.println(winner + " received the most votes!");
    }
}
