/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    //this will test your method that returns a random book quote
    @Test void testReturnsRandomPopularBookQuote() throws IOException {
        String myFilePath = "src/test/resources/recentquotes.json";
        GsonStreamer sut = new GsonStreamer(myFilePath);
        boolean gotFile = sut.getFile(myFilePath);
        assertTrue(gotFile);
        String results = sut.getRandomQuote();
        assertTrue(results.length() > 0);
    }

    @Test void testGetFileMethodThrowsIOException(){
        GsonStreamer sut = new GsonStreamer("gibberish");
        assertThrows(IOException.class, () -> {sut.getFile("gibberish");});
    }
    @Test void testGetFileMethodReturnsTrue() throws IOException {
        String myFilePath = "src/test/resources/recentquotes.json";
        GsonStreamer sut = new GsonStreamer(myFilePath);
        assertTrue(sut.getFile(myFilePath));
    }

}
